### ISSUE TITLE
Model parameter file size

### ISSUE THREAD

**Issue by thias42** [ksangeeta2429/edgel3#2]
Hi ksangeeta2429,

Thank you for making the code and models available. I am experimenting with edgel3 and noticed that the model parameter files are the same size (~35M) as the openl3 models. Shouldn't they be much smaller?

Thank you,
Matthias

**Comment by ksangeeta2429** [comment]
Hello Matthias! If you see the model size, you will see that the edgel3 audio model would have the same size as the openl3 audio model because the pruned weights i.e. weights=0 are saved as float32 values. You can use a CSR/any other sparse representation to save the non-zero weights to see the gain in static memory. 

Note: edgel3 is mainly about reducing the static memory of Audio subnetwork. You can check the EdgeL3 paper and use similar techniques to reduce the static memory of the video subnetwork. (I know I should have named it EdgeL3 Audio!)

**Comment by thias42** [comment]
Hello ksangeeta2429, I am interested in finding a more efficient / less expensive way of calculating the openl3 embeddings for music. Is your compressed network for audio env or music? How would I go about to use your model and benefit from the compressed network? I am currently using tensorflow-serving for inference. How is your work related to TensorFlow Lite?

Thank you for your help.

Matthias

**Comment by ksangeeta2429** [comment]
The edgel3 models (uploaded ones) are based on music. It is easy to convert the models to tflite models but I do not think you will benefit (yet) from using sparse models in tflite. AFAIK embedding out of convolution layer 7 (conv7) had a comparable performance as compared to the ones from conv8 (~50% of the weights come from this layer). So, you could just get rid of conv8 and quantize it to int8 with tflite to get a much smaller model.
